name: Deploy terraform backend

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-tf-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python dependencies
        working-directory: ./remote_backend_setup
        run: |
          pip install -r requirements.txt

      - name: Deploy Terraform backend
        working-directory: ./remote_backend_setup
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          echo "::add-mask::$STORAGE_ACCOUNT_NAME"
          python deploy_tf_remote_backend.py
